version: '3'

services:
  app:
    build:
      context: ./postfix
    environment:
      - DOMAIN
      - HOSTNAME
      - SMPT_PORT
      - TARGET_DOMAIN
      - TARGET_SMPT_PORT
      - TARGET_IP
    ports:
      - ${SMPT_PORT}:25

    volumes:
      - ./postfix/config:/config
      - mailqueue:/queue
      - ./ssl:/etc/ssl/certs

  opendkim:
    build:
      context: ./opendkim
    ports:
      - 8891:8891
    volumes:
      - ./opendkim/config:/config
      - ./keys:/tmp/keys
    environment:
      - DOMAIN
      - TARGET_IP

volumes:
  mailqueue:
  opendkim_socket:
